### ISSUE TITLE
Remove `sendRequest` from API, after small adjustments `yield put` should be enough

### ISSUE THREAD

**Issue by klis87** [klis87/redux-requests#276]
Initially this library didn't have `watchRequests`. In my opinion it doesn't make sense not to use it, so `sendRequest` actually now is needed only in interceptors. `sendRequest` has some special powers over direct `yield put`, like it uses saga context to avoid endless loops inside interceptors. If I could solve it differently, then `sendRequest` would become redundant. It would make promise middleware required though.

**Comment by mihaisavezi** [comment]
Depending on how you use your library, it's not redundant. My usecase is triggering requestActions within a generator, and using ```yield call(sendRequest, requestAction)``` should be blocking, whereas using put, would not be a blocking operation.

**Comment by klis87** [comment]
@mihaisavezi see putResolve in saga 1.0 or put.resolve with older version, this will do what you want together with promise middleware

**Comment by klis87** [comment]
Done in `0.28.0` together with removing sagas
