### ISSUE TITLE
please provide guide to migrate from redux-saga-requests to redux-requests

### ISSUE THREAD

**Issue by iwan-uschka** [klis87/redux-requests#350]
I am using `redux-saga-requests@0.26.1` and `redux-saga-requests-axios@0.7.7` right now and i am not (cap)able to migrate to `redux-saga-requests@0.27.0` or `redux-requests`. Breaking changes have been made i cannot see any change logs because the repository of `redux-saga-requests` has been removed.

Would you please be so kind to provide a migration guide? Thank you very much.

**Comment by klis87** [comment]
I am documenting changes in releases. Is https://github.com/klis87/redux-requests/releases/tag/redux-saga-requests%400.27.0 and https://github.com/klis87/redux-requests/releases/tag/%40redux-requests%2Fcore%400.28.0 enough to migrate?

And `redux-saga-requests` hasn't  been removed, just name of the repository was changed to `redux-requests`, the whole changelog and history is there.

Anyway, I recommend you first to migrate to 0.27 and only then to 0.28, it should be simpler then.

Be noted as well that we are approaching 1.0 and we won't have so many big breaking changes anymore, API shoudl be more or less stable now

**Comment by iwan-uschka** [comment]
Thanks for your super quick reply. I just haven't thought about checking out the tags in the "new" (renamed) repository 🤦‍♂️ Thanks for pointing that out.

I will try to migrate to 0.27 first and do the rest step by step.

I must admit that some time has passed since i added all this saga stuff into my application. **Just in case** you know an example of `redux-requests` vs. `redux-saga` let me know :)

**Comment by klis87** [comment]
You can inspect https://github.com/klis87/redux-requests/tree/master/examples for different commits, I always update examples so that they are in sync with published versions

**Comment by iwan-uschka** [comment]
I am on my way. Thanks @klis87 !!

**Comment by iwan-uschka** [comment]
Woops, it took me 3 days finally to refactor everything 😵 but in the end i was able to remove a lot of code thanks to the changes made in `redux-requests`. Thumbs up
