### ISSUE TITLE
update docs of Query in @redux-requests/react

### ISSUE THREAD

**Issue by iwan-uschka** [klis87/redux-requests#351]
`requestKey` is a valid property of `Query` but is missing in the documentation.

**Comment by iwan-uschka** [comment]
Don't know if maybe there are other properties missing :)

**Comment by iwan-uschka** [comment]
Hope it's okay if i put another typo in here: please have a look at the example in https://github.com/klis87/redux-requests#promisified-dispatches

```
store.dispatch(fetchBooks()).then(({ data, error, isAborted, action })) => {
                                                                      ^
                                                         bracket needs to be removed
```

Cheers, Mr. picky :)

**Comment by klis87** [comment]
@iwan-uschka thx! I will update the docs, good catches!

**Comment by strdr4605** [comment]
> Hope it's okay if i put another typo in here: please have a look at the example in https://github.com/klis87/redux-requests#promisified-dispatches
> 
> ```
> store.dispatch(fetchBooks()).then(({ data, error, isAborted, action })) => {
>                                                                       ^
>                                                          bracket needs to be removed
> ```
> 
> Cheers, Mr. picky :)

@iwan-uschka, you could make a PR for fixing this typo!

**Comment by klis87** [comment]
Redundant as docs were moved [here](https://redux-requests.klisiczynski.com)

**Comment by iwan-uschka** [comment]
Thx @klis87. Feel free to check again, i couldn't find any information about the `request` property in https://redux-requests.klisiczynski.com/docs/guides/usage-with-react#query.

And sorry @strdr4605, i never contributed to any public Github project (bummer) so i don't know the PR flow to be honest and there wasn't enough time the last weeks to dig into it.

**Comment by strdr4605** [comment]
@iwan-uschka no problems, we are here to learn. I encourage you to learn how to work with Github as it's an amazing experience contributing to open-source. You may check https://github.com/TUM-FAF/faf-contributions. Noticed a typo, make a PR, maintainers will be thankful.

**Comment by klis87** [comment]
@iwan-uschka right, some more props were missing too, thx!
