### ISSUE TITLE
how to read upload progress of an HTTP request

### ISSUE THREAD

**Issue by iwan-uschka** [klis87/redux-requests#380]
I want to ask how to achieve getting the upload progress of an HTTP request when using the `axios` driver and `redux-saga` with `redux-requests`.

I read something about a `redux-saga` `eventChannel` [here](https://decembersoft.com/posts/file-upload-progress-with-redux-saga/) but you need to wrap the XMLHttpRequest into it which somehow breaks the idea of using the `axios` driver.

Does "letting `redux-requests` handle upload/download progress events" has been put to any roadmap so far? Or can this already be solved?

Thx!

**Comment by klis87** [comment]
You should be able to use axios `onUploadProgress` like any other axios attribute, just try to pass it to `request` object and provide an appropriate callback

**Comment by iwan-uschka** [comment]
Jap, sure. This works. No doubt :)

`redux-requests` claims to offer

> ... AJAX requests and automatic network state management...

so i was wondering if HTTP request/response progress events could be handled like `success`, `error`, `abort` by `redux-requests`.

In the end it would be cool to not just have `pending` as a redux state property for `queries`/`mutations` but also `progress`. In my case i am not able to pass a callback as `onUploadProgress` directly (decoupling code).

**Comment by klis87** [comment]
You could also use thunk instead of normal action.

Regarding building it natively, this is a very interesting feature request! I will add it to TODO list!

**Comment by klis87** [comment]
@iwan-uschka Released in 1.3.0, see release and docs for the usage! Please let me know if it works as expected, thx again for the idea!

**Comment by iwan-uschka** [comment]
Hey @klis87, so cool to hear that a proposal i made finally made it into the library :) Just want to ask, if you think it would make sense to add `downloadProgress` and `uploadProgress` not only to `getQuery` and `getMutation` but also to `useQuery` and `useMutation`. If you agree here i can try to work on this and make a PR. Cheers

**Comment by klis87** [comment]
@iwan-uschka Hi! It was very good proposal and in the spirit this library is gonna take - declarativeness all the way! Regarding your question, it is already added to useQuery, useMutation, Query and Mutation! Perhaps I didn't make it clear enough in the docs, but it should work for all React components as well as all selectors. Typescript types are also updated, so your text editor should show those new attrs too!

**Comment by iwan-uschka** [comment]
While searching the code of installed `redux-requests` packages i noticed, that my last `yarn install` didn't work out that way. The latest versions were not installed. Sorry!

I gave it a new try but now i am getting the following error when doing a regular fetch (no upload or download progress handling activated):

```
Warning: React does not recognize the `downloadProgress` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `downloadprogress` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at Loader (https://localhost:3000/static/js/0.chunk.js:115738:29)
    at defaultProps(Loader)
    at withStyleProps(defaultProps(Loader)) (https://localhost:3000/static/js/0.chunk.js:133315:31)
    at Query (https://localhost:3000/static/js/0.chunk.js:2800:19)
    at div
    at Container (https://localhost:3000/static/js/0.chunk.js:106698:30)
    at defaultProps(Container)
    at div
    at Content (https://localhost:3000/static/js/0.chunk.js:106793:29)
    at defaultProps(Content)
    at Ads (https://localhost:3000/static/js/main.chunk.js:6815:83)
    at Route (https://localhost:3000/static/js/0.chunk.js:82186:29)
    at Switch (https://localhost:3000/static/js/0.chunk.js:82388:29)
    at div
    at Container (https://localhost:3000/static/js/0.chunk.js:106698:30)
    at defaultProps(Container)
    at div
    at Container (https://localhost:3000/static/js/0.chunk.js:106698:30)
    at defaultProps(Container)
    at Naming (https://localhost:3000/static/js/main.chunk.js:7473:88)
    at Route (https://localhost:3000/static/js/0.chunk.js:82186:29)
    at Switch (https://localhost:3000/static/js/0.chunk.js:82388:29)
    at div
    at Container (https://localhost:3000/static/js/0.chunk.js:106698:30)
    at defaultProps(Container)
    at App (https://localhost:3000/static/js/main.chunk.js:2399:3)
    at Provider (https://localhost:3000/static/js/0.chunk.js:78917:20)
    at HelmetProvider (https://localhost:3000/static/js/0.chunk.js:78197:19)
    at Router (https://localhost:3000/static/js/0.chunk.js:81821:30)
    at BrowserRouter (https://localhost:3000/static/js/0.chunk.js:81441:35)
    at Root (https://localhost:3000/static/js/main.chunk.js:11222:3)
---

  | console.<computed> | @ | index.js:1
  | overrideMethod | @ | react_devtools_backend.js:2430
  | printWarning | @ | react-dom.development.js:67
  | error | @ | react-dom.development.js:43
  | validateProperty$1 | @ | react-dom.development.js:3513
  | warnUnknownProperties | @ | react-dom.development.js:3559
  | validateProperties$2 | @ | react-dom.development.js:3583
  | validatePropertiesInDevelopment | @ | react-dom.development.js:8765
  | setInitialProperties | @ | react-dom.development.js:9041
  | finalizeInitialChildren | @ | react-dom.development.js:10201
  | completeWork | @ | react-dom.development.js:19470
  | completeUnitOfWork | @ | react-dom.development.js:22815
  | performUnitOfWork | @ | react-dom.development.js:22787
  | workLoopSync | @ | react-dom.development.js:22707
  | renderRootSync | @ | react-dom.development.js:22670
  | performSyncWorkOnRoot | @ | react-dom.development.js:22293
  | (anonymous) | @ | react-dom.development.js:11327
  | unstable_runWithPriority | @ | scheduler.development.js:646
  | runWithPriority$1 | @ | react-dom.development.js:11276
  | flushSyncCallbackQueueImpl | @ | react-dom.development.js:11322
  | flushSyncCallbackQueue | @ | react-dom.development.js:11309
  | batchedUpdates$1 | @ | react-dom.development.js:22387
  | notify | @ | Subscription.js:19
  | notifyNestedSubs | @ | Subscription.js:90
  | handleChangeWrapper | @ | Subscription.js:95
  | dispatch | @ | redux.js:222
  | e | @ | VM1883:1
  | (anonymous) | @ | create-send-requests-middleware.js:364
  | dispatch | @ | redux.js:638
  | (anonymous) | @ | create-send-requests-middleware.js:349
  | Promise.then (async) |   |  
  | (anonymous) | @ | create-send-requests-middleware.js:345
  | dispatch | @ | VM1883:1
  | (anonymous) | @ | App.jsx:34
  | invokePassiveEffectCreate | @ | react-dom.development.js:23487
  | callCallback | @ | react-dom.development.js:3945
  | invokeGuardedCallbackDev | @ | react-dom.development.js:3994
  | invokeGuardedCallback | @ | react-dom.development.js:4056
  | flushPassiveEffectsImpl | @ | react-dom.development.js:23574
  | unstable_runWithPriority | @ | scheduler.development.js:646
  | runWithPriority$1 | @ | react-dom.development.js:11276
  | flushPassiveEffects | @ | react-dom.development.js:23447
  | (anonymous) | @ | react-dom.development.js:23324
  | workLoop | @ | scheduler.development.js:590
  | flushWork | @ | scheduler.development.js:545
  | performWorkUntilDeadline | @ | scheduler.development.js:157
```

`package.json`:

```
"@redux-requests/axios": "^1.1.0",
"@redux-requests/core": "^1.3.0",
"@redux-requests/react": "^1.3.0",
"axios": "^0.21.0",
"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-redux": "^7.2.2",
"redux": "^4.0.5",
"redux-actions": "^2.6.5",
"redux-saga": "^1.1.3",
"reselect": "^4.0.0",
```

**Comment by klis87** [comment]
@iwan-uschka this is a harmless warning, but it should be fixed anyway. Could you please give me a snippet how you use Query component?

**Comment by iwan-uschka** [comment]
Hi @klis87 , thanks for taking the time. I was able to fix this by changing my `LoadingComponent` which is used in `Query`. It's important to know that a loading component like this

```
const Loader = (props) => <div {...props} />;
```

won't work anymore because we do now have some camel cased property names. I used a component provided by a UI framework so it was a little harder to find out. But in the end the error message above says it all and now i understand :)

But i got stuck again.

The action i dispatch for uploading a file looks like this:

```
{
  "type": "API/NAMING/IMPORT",
  "request": {
    "url": "/naming/bulkImport",
    "method": "POST",
    "data": formData,
    "headers": {
      "Content-Type": "multipart/form-data"
    },
    "onUploadProgress": onUploadProgress
  },
  "meta": { "measureUploadProgress": true }
}
```

`onUploadProgress` works, like you described in https://github.com/klis87/redux-requests/issues/380#issuecomment-691982651 and returns the upload progress event including `total` and `loaded`. But this

```
useMutation({ type: "API/NAMING/IMPORT" })
```

always returns

```
{loading: true, error: null, downloadProgress: null, uploadProgress: 0}
```

for some reason.

**Comment by klis87** [comment]
@iwan-uschka yeah, passing all props to div would make this warning, anyway it is not library issue

regarding your action, remove `onUploadProgress` from action, probably you overrode this handler from axios driver :)

let me know if that fixes the issue

**Comment by klis87** [comment]
definitely this is the reason, see https://github.com/klis87/redux-requests/blob/master/packages/redux-requests-axios/src/axios-driver.js#L29

**Comment by iwan-uschka** [comment]
Jap. Indeed. Thx. Case closed :)
