### ISSUE TITLE
Some headers are missing

### ISSUE THREAD

**Issue by tonitassimo** [klis87/redux-requests#386]
Hey there,

first of all thank you for developing this library!

Right now we're using redux-requests/core 1.1.1 with redux-requests/axios 1.0.0 and ran into the following issue.

We need to access the 'content-disposition' from the headers, but unfortunately the only things we can get are 'content-length' and 'content-type'. We already tried to use interceptors (attached to the axios instance or attached to the redux store), but neither of it had any effect.

Do you have any idea what we could do in order to get the 'content-disposition'? 

Many thanks in advance!

**Comment by klis87** [comment]
Hi, I am glad for a new happy User!

That's weird, I pass all headers from response, see https://github.com/klis87/redux-requests/blob/master/packages/redux-requests-axios/src/axios-driver.js#L13

Then you should see it in onSuccess like described here https://redux-requests.klisiczynski.com/docs/drivers/using-drivers#supporting-more-than-just-data

Are you sure it is not visible when console.log('response.headers') in `onSuccess`?

**Comment by klis87** [comment]
If it is not displayed, even not seen in axios interceptor, this is probably an axios issue or actually this header is not really sent, did you see it in network tab in chrome dev tools?

**Comment by klis87** [comment]
not sure but this might help you: https://github.com/axios/axios/issues/2311

**Comment by tonitassimo** [comment]
Thank you for your quick answers!

It really helped us. In our case the problem was that our backend didn't expose the header that we needed.

We had to modify the CORS policy to expose the 'content-disposition' header. Now everything works perfectly fine! :)

**Comment by klis87** [comment]
@tonitassimo cool, glad it help you!
