### ISSUE TITLE
Caching with different cacheKey

### ISSUE THREAD

**Issue by Nevenq** [klis87/redux-requests#447]
I have a question about how the cacheKey works. I have fetch action
![image](https://user-images.githubusercontent.com/38163651/108964577-746a5200-769d-11eb-9ed7-fe98d53f6268.png)

For example i need 2 requests with different teamType 0 and 1. In this case, the cache will remember the last teamType cacheKey.
![image](https://user-images.githubusercontent.com/38163651/108965006-11c58600-769e-11eb-858a-f4a94a03dc2d.png)

Expected 2 cacheKeys.

**Comment by klis87** [comment]
`cacheKey` is for cache invalidation, if you need to store 2 data for the same query type, use `requestKey`

**Comment by klis87** [comment]
`requestKey` can by used without cache even, but it is complementary with `cache` and `cacheKey`

**Comment by Nevenq** [comment]
> `cacheKey` is for cache invalidation, if you need to store 2 data for the same query type, use `requestKey`

@klis87 When i use `requestKey` it makes different query types
![image](https://user-images.githubusercontent.com/38163651/108977553-7ab2fb00-76aa-11eb-8a43-ffc1eb297c69.png)

**Comment by klis87** [comment]
@Nevenq yes, this is necessary, without requestKey there is no way to store multiple requests for the same type, without requestKey next request overrides previous data always

why designed like this? cache doesnt store any data copy

having multiple types is not an issue, just remember to pass mathing `requestKey` in `useQuery`, getQuery` or whatever you use

**Comment by Nevenq** [comment]
@klis87 I migrate from redux-saga-requests)

Well thank you. I thought I was doing something wrong. More code will have to be rewritten

**Comment by klis87** [comment]
@Nevenq ahh right, caching was refactored since then to support more cases and to be compatible with mutations :)
