### ISSUE TITLE
Bug: useQuery with autoLoad false does not allowing manually call of load function

### ISSUE THREAD

**Issue by mokabyls** [klis87/redux-requests#448]
Hi,

just find a bug with useQuery hook. If you pass autoLoad option to false and want manually call the load function, useQuery not dispatch action while autoLoad is false. Check the code bellow :

https://github.com/klis87/redux-requests/blob/0176826fd239d9e1319439cae2c96f1140728792/packages/redux-requests-react/src/use-query.js#L41-L49

To resolve this issue, we just have to remove this verification and voilà !

**Comment by klis87** [comment]
@mokabyls nice find! I will need to make sure why I even added this here. I can see the very same condition in `useEffect`. In the meantime, if you wish, you could make PR, as indeed you found the solution yourself! If not, I will do it myself in the incoming days :)

**Comment by klis87** [comment]
@mokabyls I checked and indeed it should be safe to just remove this condition like you described. Probably this line is a leftover from my prototyping.

**Comment by klis87** [comment]
Fixed and published https://github.com/klis87/redux-requests/releases/tag/%40redux-requests%2Freact%401.6.1
