### ISSUE TITLE
Bug: query state in store is not updating when meta.mutations property used

### ISSUE THREAD

**Issue by avasuro** [klis87/redux-requests#451]
If request action contains meta.mutations object then query state in store is not updating (loading is not changing to true/false)

Here is a [sandbox example](https://codesandbox.io/s/laughing-tu-ok9n9?file=/src/App.js)
See file App.js and comment/uncomment line number 19 to see the difference, and then click on button "send request" - you'll see that if line number 19 is commented - everything works find ("loading..." is displayed below the button), but if you uncomment that line - it stops working.

**Comment by klis87** [comment]
@avasuro this is a query, not a mutation. Maybe this is not documented well enough, but only mutations could have meta.mutations (and recently added subscriptions). So this combination is actually not supported. In the next major version, as createQuery and createMutation helpers will be added, this will be probably better explained.

**Comment by avasuro** [comment]
@klis87 Hm, yes, it is logical. Then this ticket can be closed.
