### ISSUE TITLE
Cannot access to documentation!

### ISSUE THREAD

**Issue by nvdnvd00** [klis87/redux-requests#536]
Seems like the documentation doesn't accessable anymore.
<img width="855" alt="CleanShot 2022-11-29 at 14 01 53@2x" src="https://user-images.githubusercontent.com/17423070/204460998-495137f3-24c0-41e9-885e-1f30c7b6942e.png">

**Comment by klis87** [comment]
Thank you for raising this. I need to prolong my domain ;) I will try to do it tomorrow. In the meantime, you can access it locally here - https://github.com/klis87/redux-requests/tree/master/docusaurus

**Comment by klis87** [comment]
The docs are available again at https://redux-requests.klisiczynski.com/ . Thx again for reporting the issue.
