### ISSUE TITLE
isAbsoluteURL dependency on axios throws module not found. 

### ISSUE THREAD

**Issue by klausbreyer** [klis87/redux-requests#544]
There is a problem with the axios dependency since (one of the last axios updates). 

With `"axios": "1.2.2"` in my dependencies, I encounter: 

```
Module not found: Error: Package path ./lib/helpers/isAbsoluteURL is not exported from package /Users/kb1/versioned/[..]pwa/node_modules/axios (see exports field in /Users/kb1/[..]pwa/node_modules/axios/package.json)
ERROR in ./node_modules/@redux-requests/fetch/es/fetch-api-driver.js 27:0-60
Module not found: Error: Package path ./lib/helpers/isAbsoluteURL is not exported from package /Users/kb1/[..]pwa/node_modules/axios (see exports field in /Users/kb1/[..]pwa/node_modules/axios/package.json)

```

With `"axios": "^0"` in my dependencies, everything is fine.

**Comment by klis87** [comment]
Thanks for reporting. It seems that this is internal axios dependency. Hopefully they just moved it to another file. If you wish, I will gladly accept PR, otherwise I will try to fix it myself in the following days.

**Comment by klausbreyer** [comment]
Not sure, though. The file is at the old place. For me, at first sight, it seems this is caused by axios introducing [exports fields in the package.json](https://github.com/axios/axios/blob/v1.x/package.json) and tbh I am not sure what a right solution could look like in the context of the redux-requests project.

**Comment by klis87** [comment]
No problem! I will try to take a look soon, as a last resort, I will just copy this util to this project if we were not able to reuse it from axios anymore.

**Comment by klis87** [comment]
I actually removed axios dependency, so it won't cause similar issues in the future. Released at https://github.com/klis87/redux-requests/releases/tag/%40redux-requests%2Ffetch%401.1.1 Thanks again for reporting!

**Comment by klausbreyer** [comment]
thanks for the lighting fast response! :)
